import type { ReportPair } from "./types";

export const reportPairs: ReportPair[] = [
  {
    id: "thule-2024-2023",
    company: "Thule Group",
    ticker: "THULE",
    market: "Nasdaq Stockholm",
    accent: "#111111",
    latest: {
      year: 2024,
      language: "en",
      filename: "thule-annual-report-2024.pdf",
      url: "https://www.thulegroup.com/sites/thulegroup/files/pr/20250407-9b8e015d-1923-44d2-9106-d4510b04a96b-1.pdf",
    },
    previous: {
      year: 2023,
      language: "en",
      filename: "thule-annual-report-2023.pdf",
      url: "https://www.thulegroup.com/sites/thulegroup/files/pr/20240405-1b0268b5-627a-42f2-94e5-b26d485a5ed5-1.pdf",
    },
    sourceUrl: "https://www.thulegroup.com/en/reports",
  },
  {
    id: "hms-2024-2023",
    company: "HMS Networks",
    ticker: "HMS",
    market: "Nasdaq Stockholm",
    accent: "#e51f2f",
    latest: {
      year: 2024,
      language: "en",
      filename: "hms-networks-annual-report-2024.pdf",
      url: "https://hmsnetworks.blob.core.windows.net/nlw/docs/default-source/finance/annual-reports/annual-reports-%28english%29/hms-networks-annual-report-2024.pdf?sfvrsn=6438458b_5",
    },
    previous: {
      year: 2023,
      language: "en",
      filename: "hms-networks-annual-report-2023.pdf",
      url: "https://hmsnetworks.blob.core.windows.net/nlw/docs/default-source/finance/annual-reports/annual-reports-%28english%29/hms-networks-annual-report-2023.pdf?sfvrsn=84496d7_11",
    },
    sourceUrl: "https://www.hms-networks.com/financial-reports",
  },
  {
    id: "engcon-2024-2023",
    company: "engcon",
    ticker: "ENGCON B",
    market: "Nasdaq Stockholm",
    accent: "#ffd600",
    latest: {
      year: 2024,
      language: "en",
      filename: "engcon-annual-report-2024.pdf",
      url: "https://www.engcongroup.com/wp-content/uploads/engcon-engcon-publishes-its-2024-annual-and-sustainability-report-250321.pdf",
    },
    previous: {
      year: 2023,
      language: "en",
      filename: "engcon-annual-report-2023.pdf",
      url: "https://www.engcongroup.com/wp-content/uploads/engcon-engcon-publishes-its-2023-annual-and-sustainability-report-240327.pdf",
    },
    sourceUrl: "https://www.engcongroup.com/investors/reports-and-presentations/",
  },
  {
    id: "thule-2023-2022",
    company: "Thule Group",
    ticker: "THULE",
    market: "Nasdaq Stockholm",
    accent: "#111111",
    latest: {
      year: 2023,
      language: "en",
      filename: "thule-annual-report-2023.pdf",
      url: "https://www.thulegroup.com/sites/thulegroup/files/pr/20240405-1b0268b5-627a-42f2-94e5-b26d485a5ed5-1.pdf",
    },
    previous: {
      year: 2022,
      language: "en",
      filename: "thule-annual-report-2022.pdf",
      url: "https://www.thulegroup.com/sites/thulegroup/files/pr/20230331-eb5cbba9-6537-41f4-b46b-d30106eebb87-1.pdf",
    },
    sourceUrl: "https://www.thulegroup.com/en/reports",
  },
  {
    id: "hms-2023-2022",
    company: "HMS Networks",
    ticker: "HMS",
    market: "Nasdaq Stockholm",
    accent: "#e51f2f",
    latest: {
      year: 2023,
      language: "en",
      filename: "hms-networks-annual-report-2023.pdf",
      url: "https://hmsnetworks.blob.core.windows.net/nlw/docs/default-source/finance/annual-reports/annual-reports-%28english%29/hms-networks-annual-report-2023.pdf?sfvrsn=84496d7_11",
    },
    previous: {
      year: 2022,
      language: "en",
      filename: "hms-networks-annual-report-2022.pdf",
      url: "https://hmsnetworks.blob.core.windows.net/nlw/docs/default-source/finance/annual-reports/annual-reports-%28english%29/hms-networks-annual-report-2022.pdf?sfvrsn=bea7b6d7_11",
    },
    sourceUrl: "https://www.hms-networks.com/financial-reports",
  },
  {
    id: "engcon-2023-2022",
    company: "engcon",
    ticker: "ENGCON B",
    market: "Nasdaq Stockholm",
    accent: "#ffd600",
    latest: {
      year: 2023,
      language: "en",
      filename: "engcon-annual-report-2023.pdf",
      url: "https://www.engcongroup.com/wp-content/uploads/engcon-engcon-publishes-its-2023-annual-and-sustainability-report-240327.pdf",
    },
    previous: {
      year: 2022,
      language: "en",
      filename: "engcon-annual-report-2022.pdf",
      url: "https://www.engcongroup.com/wp-content/uploads/engcon-engcon-publishes-its-2022-annual-and-sustainability-report-230330.pdf",
    },
    sourceUrl: "https://www.engcongroup.com/investors/reports-and-presentations/",
  },
];
